"""Полный REST API (как backend/api) для фронта cyberos."""
from django.urls import path

from api import sql_auth, sql_extras, sql_views

urlpatterns = [
    path("health", sql_views.health),
    path("system/diagnostics", sql_views.system_diagnostics),
    path("auth/login", sql_auth.auth_login),
    path("player/login", sql_views.player_login),
    path("player/register", sql_views.player_register),
    path("auth/me", sql_auth.auth_me),
    path("live", sql_extras.live_snapshot),
    path("stats/export.csv", sql_extras.stats_export_csv),

    path("zones", sql_views.zones),
    path("zones/<int:pk>", sql_views.zone_detail),
    path("workstations/zone/<int:zone_id>", sql_views.workstations_by_zone),
    path("workstations/<int:pk>/command", sql_extras.workstation_command),
    path("workstations", sql_views.workstations),
    path("workstations/<int:pk>", sql_views.workstation_detail),
    path("agent/pending", sql_extras.agent_pending),
    path("agent/ack", sql_extras.agent_ack),
    path("agent/heartbeat", sql_extras.agent_heartbeat),
    path("clients/search", sql_views.clients_search),
    path("clients", sql_views.clients),
    path("clients/<int:pk>", sql_views.client_detail),
    path("tariffs", sql_views.tariffs),
    path("tariffs/<int:pk>", sql_views.tariff_detail),
    path("sessions/active", sql_views.sessions_active),
    path("sessions", sql_views.sessions),
    path("sessions/<int:pk>/end", sql_views.session_end),
    path("sessions/<int:pk>/extend", sql_views.session_extend),
    path("sessions/<int:pk>/pause", sql_views.session_pause),
    path("sessions/<int:pk>/resume", sql_views.session_resume),
    path("products", sql_views.products),
    path("products/<int:pk>", sql_views.product_detail),
    path("sales/<int:pk>/items", sql_views.sale_items),
    path("sales", sql_views.sales),
    path("promos/apply", sql_views.promos_apply),
    path("promos", sql_views.promos),
    path("promos/<int:pk>", sql_views.promo_detail),

    path("tasks", sql_views.tasks),
    path("tasks/<int:pk>/complete", sql_views.task_complete),
    path("tasks/<int:pk>/reopen", sql_views.task_reopen),
    path("tasks/<int:pk>", sql_views.task_detail),
    path("settings", sql_views.settings_view),
    path("notifications/read", sql_views.notifications_mark_read),
    path("notifications", sql_views.notifications_feed),
    path("stats/dashboard", sql_views.stats_dashboard),
    path("stats/analytics", sql_views.stats_analytics),
    path("orders", sql_views.orders),
    path("orders/<int:pk>/complete", sql_views.order_complete),
    path("orders/<int:pk>/cancel", sql_views.order_cancel),
]
